// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Receipt Processor
 *
 * A simple receipt processor
 *
 * API version: 1.0.0
 */

package openapi




type GetReceiptPoints200Response struct {

	Points int64 `json:"points,omitempty"`
}

// AssertGetReceiptPoints200ResponseRequired checks if the required fields are not zero-ed
func AssertGetReceiptPoints200ResponseRequired(obj GetReceiptPoints200Response) error {
	return nil
}

// AssertGetReceiptPoints200ResponseConstraints checks if the values respects the defined constraints
func AssertGetReceiptPoints200ResponseConstraints(obj GetReceiptPoints200Response) error {
	return nil
}
