// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Receipt Processor
 *
 * A simple receipt processor
 *
 * API version: 1.0.0
 */

package openapi




type ProcessReceipt200Response struct {

	Id string `json:"id" validate:"regexp=^\\\\S+$"`
}

// AssertProcessReceipt200ResponseRequired checks if the required fields are not zero-ed
func AssertProcessReceipt200ResponseRequired(obj ProcessReceipt200Response) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertProcessReceipt200ResponseConstraints checks if the values respects the defined constraints
func AssertProcessReceipt200ResponseConstraints(obj ProcessReceipt200Response) error {
	return nil
}
